# Generated by Django 3.1.2 on 2020-10-11 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201011_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Video',
        ),
    ]
